required:
  host:
  port: 22
  username:
  path:
  auth:
    - password: 1
    - ras: 2
  password:
    dependencyKey: auth
    dependencyValue: 1
  ras:
    dependencyKey: auth
    dependencyValue: 2
