required:
  host:
  port: 22
  username:
  path:
  auth:
    - password: 1
    - rsaPath: 2
  password:
    dependencyKey: auth
    dependencyValue: 1
  rsaPath:
    dependencyKey: auth
    dependencyValue: 2
